//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.Web.Business.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:20001/ReportingServices.asmx")]
        public string AS_Web_Business_ReportService_fdc_ReportingServices {
            get {
                return ((string)(this["AS_Web_Business_ReportService_fdc_ReportingServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:64001/AS.WS.Services/fdc_RiskServices.asmx")]
        public string AS_Web_Business_RiskService_fdc_RiskServices {
            get {
                return ((string)(this["AS_Web_Business_RiskService_fdc_RiskServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:64001/AS.WS.Services/fdc_TicketServices.asmx")]
        public string AS_Web_Business_TicketService_fdc_TicketServices {
            get {
                return ((string)(this["AS_Web_Business_TicketService_fdc_TicketServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:64001/AS.WS.Services/fdc_ProReportServices.asmx")]
        public string AS_Web_Business_ProReportService_fdc_ProReportServices {
            get {
                return ((string)(this["AS_Web_Business_ProReportService_fdc_ProReportServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:64001/AS.WS.Services/fdc_TaxServices.asmx")]
        public string AS_Web_Business_TaxService_fdc_TaxServices {
            get {
                return ((string)(this["AS_Web_Business_TaxService_fdc_TaxServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:64001/AS.WS.Services/fdc_ReportingServices.asmx")]
        public string AS_Web_Business_ReportService_fdc_ReportingServices1 {
            get {
                return ((string)(this["AS_Web_Business_ReportService_fdc_ReportingServices1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.119.5/DocProcessor.asmx")]
        public string AS_Web_Business_DocWebServices_DocProcessor {
            get {
                return ((string)(this["AS_Web_Business_DocWebServices_DocProcessor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pcireskin-ws-qa.local/v100_int/Business.asmx")]
        public string AS_Web_Business_PciWebServices_PCIServices {
            get {
                return ((string)(this["AS_Web_Business_PciWebServices_PCIServices"]));
            }
        }
    }
}
