//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace AS.Web.Business.DocWebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocProcessorSoap", Namespace="DDS")]
    public partial class DocProcessor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckExistFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithDocCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithFilePathOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithDocCategoryEncryptedOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithFilePathEncryptedOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDocumentByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDocumentByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileStorageByRecIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocumentListByCategoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocProcessor() {
            this.Url = global::AS.Web.Business.Properties.Settings.Default.AS_Web_Business_DocWebServices_DocProcessor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CheckExistFileCompletedEventHandler CheckExistFileCompleted;
        
        /// <remarks/>
        public event UploadFileWithDocCategoryCompletedEventHandler UploadFileWithDocCategoryCompleted;
        
        /// <remarks/>
        public event UploadFileWithFilePathCompletedEventHandler UploadFileWithFilePathCompleted;
        
        /// <remarks/>
        public event UploadFileWithDocCategoryEncryptedCompletedEventHandler UploadFileWithDocCategoryEncryptedCompleted;
        
        /// <remarks/>
        public event UploadFileWithFilePathEncryptedCompletedEventHandler UploadFileWithFilePathEncryptedCompleted;
        
        /// <remarks/>
        public event DeleteDocumentByIDCompletedEventHandler DeleteDocumentByIDCompleted;
        
        /// <remarks/>
        public event UpdateDocumentByIDCompletedEventHandler UpdateDocumentByIDCompleted;
        
        /// <remarks/>
        public event GetFileStorageByRecIDCompletedEventHandler GetFileStorageByRecIDCompleted;
        
        /// <remarks/>
        public event GetDocumentListByCategoryCompletedEventHandler GetDocumentListByCategoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/HelloWorld", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/CheckExistFile", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckExistFile(string clientid, string filename) {
            object[] results = this.Invoke("CheckExistFile", new object[] {
                        clientid,
                        filename});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckExistFileAsync(string clientid, string filename) {
            this.CheckExistFileAsync(clientid, filename, null);
        }
        
        /// <remarks/>
        public void CheckExistFileAsync(string clientid, string filename, object userState) {
            if ((this.CheckExistFileOperationCompleted == null)) {
                this.CheckExistFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckExistFileOperationCompleted);
            }
            this.InvokeAsync("CheckExistFile", new object[] {
                        clientid,
                        filename}, this.CheckExistFileOperationCompleted, userState);
        }
        
        private void OnCheckExistFileOperationCompleted(object arg) {
            if ((this.CheckExistFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckExistFileCompleted(this, new CheckExistFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/UploadFileWithDocCategory", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFileWithDocCategory(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] objFile, string RemoteAddress, out long DocId, out string strReturnStatus, out string strStorageFileName) {
            object[] results = this.Invoke("UploadFileWithDocCategory", new object[] {
                        strClient,
                        strEntity,
                        strDocumentCategory,
                        strFileName,
                        strDescription,
                        status,
                        strRetention,
                        objFile,
                        RemoteAddress});
            DocId = ((long)(results[1]));
            strReturnStatus = ((string)(results[2]));
            strStorageFileName = ((string)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithDocCategoryAsync(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, byte[] objFile, string RemoteAddress) {
            this.UploadFileWithDocCategoryAsync(strClient, strEntity, strDocumentCategory, strFileName, strDescription, status, strRetention, objFile, RemoteAddress, null);
        }
        
        /// <remarks/>
        public void UploadFileWithDocCategoryAsync(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, byte[] objFile, string RemoteAddress, object userState) {
            if ((this.UploadFileWithDocCategoryOperationCompleted == null)) {
                this.UploadFileWithDocCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithDocCategoryOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithDocCategory", new object[] {
                        strClient,
                        strEntity,
                        strDocumentCategory,
                        strFileName,
                        strDescription,
                        status,
                        strRetention,
                        objFile,
                        RemoteAddress}, this.UploadFileWithDocCategoryOperationCompleted, userState);
        }
        
        private void OnUploadFileWithDocCategoryOperationCompleted(object arg) {
            if ((this.UploadFileWithDocCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithDocCategoryCompleted(this, new UploadFileWithDocCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/UploadFileWithFilePath", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFileWithFilePath(string client, string userName, string dirPath, string fileName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileContent, string docCategory, string remoteAddress, out long docID) {
            object[] results = this.Invoke("UploadFileWithFilePath", new object[] {
                        client,
                        userName,
                        dirPath,
                        fileName,
                        fileContent,
                        docCategory,
                        remoteAddress});
            docID = ((long)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithFilePathAsync(string client, string userName, string dirPath, string fileName, byte[] fileContent, string docCategory, string remoteAddress) {
            this.UploadFileWithFilePathAsync(client, userName, dirPath, fileName, fileContent, docCategory, remoteAddress, null);
        }
        
        /// <remarks/>
        public void UploadFileWithFilePathAsync(string client, string userName, string dirPath, string fileName, byte[] fileContent, string docCategory, string remoteAddress, object userState) {
            if ((this.UploadFileWithFilePathOperationCompleted == null)) {
                this.UploadFileWithFilePathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithFilePathOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithFilePath", new object[] {
                        client,
                        userName,
                        dirPath,
                        fileName,
                        fileContent,
                        docCategory,
                        remoteAddress}, this.UploadFileWithFilePathOperationCompleted, userState);
        }
        
        private void OnUploadFileWithFilePathOperationCompleted(object arg) {
            if ((this.UploadFileWithFilePathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithFilePathCompleted(this, new UploadFileWithFilePathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/UploadFileWithDocCategoryEncrypted", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFileWithDocCategoryEncrypted(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] objFile, string RemoteAddress, out long DocId, out string strReturnStatus, out string strStorageFileName) {
            object[] results = this.Invoke("UploadFileWithDocCategoryEncrypted", new object[] {
                        strClient,
                        strEntity,
                        strDocumentCategory,
                        strFileName,
                        strDescription,
                        status,
                        strRetention,
                        objFile,
                        RemoteAddress});
            DocId = ((long)(results[1]));
            strReturnStatus = ((string)(results[2]));
            strStorageFileName = ((string)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithDocCategoryEncryptedAsync(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, byte[] objFile, string RemoteAddress) {
            this.UploadFileWithDocCategoryEncryptedAsync(strClient, strEntity, strDocumentCategory, strFileName, strDescription, status, strRetention, objFile, RemoteAddress, null);
        }
        
        /// <remarks/>
        public void UploadFileWithDocCategoryEncryptedAsync(string strClient, string strEntity, string strDocumentCategory, string strFileName, string strDescription, string status, string strRetention, byte[] objFile, string RemoteAddress, object userState) {
            if ((this.UploadFileWithDocCategoryEncryptedOperationCompleted == null)) {
                this.UploadFileWithDocCategoryEncryptedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithDocCategoryEncryptedOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithDocCategoryEncrypted", new object[] {
                        strClient,
                        strEntity,
                        strDocumentCategory,
                        strFileName,
                        strDescription,
                        status,
                        strRetention,
                        objFile,
                        RemoteAddress}, this.UploadFileWithDocCategoryEncryptedOperationCompleted, userState);
        }
        
        private void OnUploadFileWithDocCategoryEncryptedOperationCompleted(object arg) {
            if ((this.UploadFileWithDocCategoryEncryptedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithDocCategoryEncryptedCompleted(this, new UploadFileWithDocCategoryEncryptedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/UploadFileWithFilePathEncrypted", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFileWithFilePathEncrypted(string client, string userName, string dirPath, string fileName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileContent, string docCategory, string remoteAddress, out long docID) {
            object[] results = this.Invoke("UploadFileWithFilePathEncrypted", new object[] {
                        client,
                        userName,
                        dirPath,
                        fileName,
                        fileContent,
                        docCategory,
                        remoteAddress});
            docID = ((long)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithFilePathEncryptedAsync(string client, string userName, string dirPath, string fileName, byte[] fileContent, string docCategory, string remoteAddress) {
            this.UploadFileWithFilePathEncryptedAsync(client, userName, dirPath, fileName, fileContent, docCategory, remoteAddress, null);
        }
        
        /// <remarks/>
        public void UploadFileWithFilePathEncryptedAsync(string client, string userName, string dirPath, string fileName, byte[] fileContent, string docCategory, string remoteAddress, object userState) {
            if ((this.UploadFileWithFilePathEncryptedOperationCompleted == null)) {
                this.UploadFileWithFilePathEncryptedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithFilePathEncryptedOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithFilePathEncrypted", new object[] {
                        client,
                        userName,
                        dirPath,
                        fileName,
                        fileContent,
                        docCategory,
                        remoteAddress}, this.UploadFileWithFilePathEncryptedOperationCompleted, userState);
        }
        
        private void OnUploadFileWithFilePathEncryptedOperationCompleted(object arg) {
            if ((this.UploadFileWithFilePathEncryptedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithFilePathEncryptedCompleted(this, new UploadFileWithFilePathEncryptedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/DeleteDocumentByID", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteDocumentByID(string strClient, string strEntity, string recid) {
            object[] results = this.Invoke("DeleteDocumentByID", new object[] {
                        strClient,
                        strEntity,
                        recid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDocumentByIDAsync(string strClient, string strEntity, string recid) {
            this.DeleteDocumentByIDAsync(strClient, strEntity, recid, null);
        }
        
        /// <remarks/>
        public void DeleteDocumentByIDAsync(string strClient, string strEntity, string recid, object userState) {
            if ((this.DeleteDocumentByIDOperationCompleted == null)) {
                this.DeleteDocumentByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDocumentByIDOperationCompleted);
            }
            this.InvokeAsync("DeleteDocumentByID", new object[] {
                        strClient,
                        strEntity,
                        recid}, this.DeleteDocumentByIDOperationCompleted, userState);
        }
        
        private void OnDeleteDocumentByIDOperationCompleted(object arg) {
            if ((this.DeleteDocumentByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDocumentByIDCompleted(this, new DeleteDocumentByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/UpdateDocumentByID", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDocumentByID(string strClient, string strEntity, string recid, string desc) {
            object[] results = this.Invoke("UpdateDocumentByID", new object[] {
                        strClient,
                        strEntity,
                        recid,
                        desc});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDocumentByIDAsync(string strClient, string strEntity, string recid, string desc) {
            this.UpdateDocumentByIDAsync(strClient, strEntity, recid, desc, null);
        }
        
        /// <remarks/>
        public void UpdateDocumentByIDAsync(string strClient, string strEntity, string recid, string desc, object userState) {
            if ((this.UpdateDocumentByIDOperationCompleted == null)) {
                this.UpdateDocumentByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDocumentByIDOperationCompleted);
            }
            this.InvokeAsync("UpdateDocumentByID", new object[] {
                        strClient,
                        strEntity,
                        recid,
                        desc}, this.UpdateDocumentByIDOperationCompleted, userState);
        }
        
        private void OnUpdateDocumentByIDOperationCompleted(object arg) {
            if ((this.UpdateDocumentByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDocumentByIDCompleted(this, new UpdateDocumentByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/GetFileStorageByRecID", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFileStorageByRecID(string recid) {
            object[] results = this.Invoke("GetFileStorageByRecID", new object[] {
                        recid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileStorageByRecIDAsync(string recid) {
            this.GetFileStorageByRecIDAsync(recid, null);
        }
        
        /// <remarks/>
        public void GetFileStorageByRecIDAsync(string recid, object userState) {
            if ((this.GetFileStorageByRecIDOperationCompleted == null)) {
                this.GetFileStorageByRecIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileStorageByRecIDOperationCompleted);
            }
            this.InvokeAsync("GetFileStorageByRecID", new object[] {
                        recid}, this.GetFileStorageByRecIDOperationCompleted, userState);
        }
        
        private void OnGetFileStorageByRecIDOperationCompleted(object arg) {
            if ((this.GetFileStorageByRecIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileStorageByRecIDCompleted(this, new GetFileStorageByRecIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DDS/GetDocumentListByCategory", RequestNamespace="DDS", ResponseNamespace="DDS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DocumentMetadataInfo[] GetDocumentListByCategory(string clientID, string entityID, string docCategory, int maxReturn) {
            object[] results = this.Invoke("GetDocumentListByCategory", new object[] {
                        clientID,
                        entityID,
                        docCategory,
                        maxReturn});
            return ((DocumentMetadataInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDocumentListByCategoryAsync(string clientID, string entityID, string docCategory, int maxReturn) {
            this.GetDocumentListByCategoryAsync(clientID, entityID, docCategory, maxReturn, null);
        }
        
        /// <remarks/>
        public void GetDocumentListByCategoryAsync(string clientID, string entityID, string docCategory, int maxReturn, object userState) {
            if ((this.GetDocumentListByCategoryOperationCompleted == null)) {
                this.GetDocumentListByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocumentListByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetDocumentListByCategory", new object[] {
                        clientID,
                        entityID,
                        docCategory,
                        maxReturn}, this.GetDocumentListByCategoryOperationCompleted, userState);
        }
        
        private void OnGetDocumentListByCategoryOperationCompleted(object arg) {
            if ((this.GetDocumentListByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocumentListByCategoryCompleted(this, new GetDocumentListByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DDS")]
    public partial class DocumentMetadataInfo {
        
        private long recIdField;
        
        private int dDSClientField;
        
        private int retentionDaysField;
        
        private int processingFlagField;
        
        private System.DateTime dateUploadedField;
        
        private System.DateTime expirationDateField;
        
        private string entityIDField;
        
        private string storageFileNameField;
        
        private string documentCategoryField;
        
        private string documentStatusField;
        
        private string documentNameField;
        
        private string displayDescriptionField;
        
        /// <remarks/>
        public long RecId {
            get {
                return this.recIdField;
            }
            set {
                this.recIdField = value;
            }
        }
        
        /// <remarks/>
        public int DDSClient {
            get {
                return this.dDSClientField;
            }
            set {
                this.dDSClientField = value;
            }
        }
        
        /// <remarks/>
        public int RetentionDays {
            get {
                return this.retentionDaysField;
            }
            set {
                this.retentionDaysField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessingFlag {
            get {
                return this.processingFlagField;
            }
            set {
                this.processingFlagField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateUploaded {
            get {
                return this.dateUploadedField;
            }
            set {
                this.dateUploadedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string EntityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
        
        /// <remarks/>
        public string StorageFileName {
            get {
                return this.storageFileNameField;
            }
            set {
                this.storageFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentCategory {
            get {
                return this.documentCategoryField;
            }
            set {
                this.documentCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentStatus {
            get {
                return this.documentStatusField;
            }
            set {
                this.documentStatusField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayDescription {
            get {
                return this.displayDescriptionField;
            }
            set {
                this.displayDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckExistFileCompletedEventHandler(object sender, CheckExistFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckExistFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckExistFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadFileWithDocCategoryCompletedEventHandler(object sender, UploadFileWithDocCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithDocCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithDocCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long DocId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strReturnStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string strStorageFileName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadFileWithFilePathCompletedEventHandler(object sender, UploadFileWithFilePathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithFilePathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithFilePathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long docID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadFileWithDocCategoryEncryptedCompletedEventHandler(object sender, UploadFileWithDocCategoryEncryptedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithDocCategoryEncryptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithDocCategoryEncryptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long DocId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strReturnStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string strStorageFileName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadFileWithFilePathEncryptedCompletedEventHandler(object sender, UploadFileWithFilePathEncryptedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithFilePathEncryptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithFilePathEncryptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long docID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteDocumentByIDCompletedEventHandler(object sender, DeleteDocumentByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDocumentByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDocumentByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateDocumentByIDCompletedEventHandler(object sender, UpdateDocumentByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDocumentByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDocumentByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetFileStorageByRecIDCompletedEventHandler(object sender, GetFileStorageByRecIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileStorageByRecIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileStorageByRecIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDocumentListByCategoryCompletedEventHandler(object sender, GetDocumentListByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocumentListByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocumentListByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DocumentMetadataInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DocumentMetadataInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591