//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceApi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceApi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AS.VW.Api.Validation.Resources.ResourceApi", typeof(ResourceApi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be greater than the {1}.
        /// </summary>
        public static string GReportFilter_FromValueGreaterToValue {
            get {
                return ResourceManager.GetString("GReportFilter_FromValueGreaterToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not in the correct format..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9a-zA-Z]+)$.
        /// </summary>
        public static string Regexp_AlphaCharacters {
            get {
                return ResourceManager.GetString("Regexp_AlphaCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9]+)$.
        /// </summary>
        public static string Regexp_Numeric {
            get {
                return ResourceManager.GetString("Regexp_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `~!@#$%^&amp;*()_+=|[]{}:;&apos;?/\\&gt;&lt;.,-\&quot;.
        /// </summary>
        public static string Regexp_SpecialCharacters {
            get {
                return ResourceManager.GetString("Regexp_SpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `~!@#$%^&amp;*()_+=|[]{}:;&apos;?/\\&gt;&lt;.,\&quot;.
        /// </summary>
        public static string Regexp_SpecialCharactersExceptHyphen {
            get {
                return ResourceManager.GetString("Regexp_SpecialCharactersExceptHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `~!@#$%^&amp;*()_+=|[]{}:;&apos;?/\\&gt;&lt;,\&quot;.
        /// </summary>
        public static string Regexp_SubClient {
            get {
                return ResourceManager.GetString("Regexp_SubClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: This is required param.
        /// </summary>
        public static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the larger date range search at least one of the following parameters is required to complete this request: HierarchyFilterMode and HierarchyFilterValue, First6CardNumber, Last4CardNumber, AuthorizationNumber.
        /// </summary>
        public static string TransactionSearch_MSG_ConditionGT90Days {
            get {
                return ResourceManager.GetString("TransactionSearch_MSG_ConditionGT90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to perform a search, one or more of the following parameters must contain a value: HierarchyFilterMode and HierarchyFilterValue, First6CardNumber, Last4CardNumber,TransactionAmout (&quot;Equal To&quot; Search Only).
        /// </summary>
        public static string TransactionSearch_MSG_ConditionLTOEQ90Days {
            get {
                return ResourceManager.GetString("TransactionSearch_MSG_ConditionLTOEQ90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERCHANTNAME and LAST6MERCHNUMBER do not allow .
        /// </summary>
        public static string Validator_Card_Sum_Hier_Mode {
            get {
                return ResourceManager.GetString("Validator_Card_Sum_Hier_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationException.
        /// </summary>
        public static string Validator_EC_Default {
            get {
                return ResourceManager.GetString("Validator_EC_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThan.
        /// </summary>
        public static string Validator_EC_GreaterThan {
            get {
                return ResourceManager.GetString("Validator_EC_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidCharacter.
        /// </summary>
        public static string Validator_EC_InvalidCharacter {
            get {
                return ResourceManager.GetString("Validator_EC_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFormat.
        /// </summary>
        public static string Validator_EC_InvalidFormat {
            get {
                return ResourceManager.GetString("Validator_EC_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Validator_EC_Length {
            get {
                return ResourceManager.GetString("Validator_EC_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanOrEqualTo.
        /// </summary>
        public static string Validator_EC_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Validator_EC_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEmpty.
        /// </summary>
        public static string Validator_EC_NotEmpty {
            get {
                return ResourceManager.GetString("Validator_EC_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotMetCondition.
        /// </summary>
        public static string Validator_EC_NotMetCondition {
            get {
                return ResourceManager.GetString("Validator_EC_NotMetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotNull.
        /// </summary>
        public static string Validator_EC_NotNull {
            get {
                return ResourceManager.GetString("Validator_EC_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyAllowNumbers.
        /// </summary>
        public static string Validator_EC_OnlyAllowNumbers {
            get {
                return ResourceManager.GetString("Validator_EC_OnlyAllowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        public static string Validator_EC_Predicate {
            get {
                return ResourceManager.GetString("Validator_EC_Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be {MaxLength} characters in length. You entered {TotalLength} characters..
        /// </summary>
        public static string Validator_MSG_ExactLength {
            get {
                return ResourceManager.GetString("Validator_MSG_ExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; must be greater than the min date.
        /// </summary>
        public static string Validator_MSG_GreaterThanMinDate {
            get {
                return ResourceManager.GetString("Validator_MSG_GreaterThanMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; have invalid character..
        /// </summary>
        public static string Validator_MSG_InvalidCharacter {
            get {
                return ResourceManager.GetString("Validator_MSG_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not in the correct format..
        /// </summary>
        public static string Validator_MSG_InvalidFormat {
            get {
                return ResourceManager.GetString("Validator_MSG_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters..
        /// </summary>
        public static string Validator_MSG_Length {
            get {
                return ResourceManager.GetString("Validator_MSG_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; cannot be greater than the today.
        /// </summary>
        public static string Validator_MSG_LessOrEqualToday {
            get {
                return ResourceManager.GetString("Validator_MSG_LessOrEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; not allow null.
        /// </summary>
        public static string Validator_MSG_NotNull {
            get {
                return ResourceManager.GetString("Validator_MSG_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; are allowed only numbers.
        /// </summary>
        public static string Validator_MSG_OnlyAllowNumbers {
            get {
                return ResourceManager.GetString("Validator_MSG_OnlyAllowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit search to 720 days.
        /// </summary>
        public static string Validator_ninetydays {
            get {
                return ResourceManager.GetString("Validator_ninetydays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        public static string Validator_Separator {
            get {
                return ResourceManager.GetString("Validator_Separator", resourceCulture);
            }
        }
    }
}
