<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="coverlet.msbuild" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AS.Web.Business\AS.Web.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AS.Common">
      <HintPath>..\Libraries\UpgradeDllForSonarIssues\AS.Common.dll</HintPath>
    </Reference>
    <Reference Include="AS.Controls">
      <HintPath>..\..\3rdLibrary\Aperia\VisionWeb\Webform\AS.Controls.dll</HintPath>
    </Reference>
    <Reference Include="ComponentSpace.SAML2">
      <HintPath>..\Libraries\componentspace.saml2.dll</HintPath>
    </Reference>
    <Reference Include="itextsharp">
      <HintPath>..\Libraries\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="log4net">
      <HintPath>..\..\3rdLibrary\log4net\2.0.15\log4net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
